language: python
python:
- 2.7
- 3.2
- 3.3
- 3.4
- 3.5
- 3.6
deploy:
  provider: pypi
  user: scottphilip
  password:
    secure: iIjdhMrT41XH/kI/yukfGA8M4XxeDvbuqMZu+J3QNKQn0GWJrqoDOReQTbQ2LwqI/gbLPckZ4oG4JPiF+SVbqo5az2jcEw2bt6wqTvGQgQ0uPl/j7SMv7l2atJpDP0BhGACkQekR7iB6f029ekFP19VnQaVywWfkQvzunDKwe95tIg3E6K2Do1LTTOIoom1tBOqvcCXptj225zb9rAcdzGZMwqUfmsjrSTgqAV3eHqOsb+UBKdwM5nfyyYuuTfTuOjAneGp8O4lUF70Qk94Ucg7mSLa0//ZbQ8hJax9lVhZeHs307277gXlRU8yuiLYyuJ8g2VLbp4eIt3g+llEB9Tvq49aTjwSUL+82aycvsnk39g8RElMg+F38JtxFwVTN7ySmz+V/yNYBvPpQ89ebJccKMFBCAaapD2Iv55VWDMImwv9sMFoaM87dTTvC6OEJ06xK0bp5q1F2qerEqwwTw/g/NdNkeCj10Sg45p+hkQehNUeFUOhXyoKwMGK4ptVyC3yP9AoLacNeTcN7JdExMGWA6bp6tlzIK2DVifRNNoevgQeIuXHUzWLKdichyeZbmCmOlHIUbEFZ3gMttUGiqnQBlMTtSU6l/hpLa90CCnkmr1A59fyr/rmSwd5gkmcaMnI8eDVfaneeD5hOO/nccau6NbMzoPY03QolIHt+vVM=
  on:
    tags: true
    branch: 0.1
